[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@types/react"

[[plugins]]
package = "@types/node"

[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"